### ISSUE TITLE
make install fails on OSX

### ISSUE THREAD

**Issue by thanethomson** [cybergarage/mupnpc#11]
For some reason `make install` fails on OSX (10.9.3):

    Making install in include
    make[2]: Nothing to be done for `install-exec-am'.
     -d '/usr/local/include'
    /bin/sh: -d: command not found
    make[2]: *** [install-nobase_includeHEADERS] Error 1
    make[1]: *** [install-am] Error 2
    make: *** [install-recursive] Error 1

It appears as though the generated Makefile has an invalid MKDIR_P setting:

    MKDIR_P =  -d

To get my installation going I manually had to `sed` all of the generated `Makefile`s in the project to make use of the `config/install-sh` script, but there's most likely a much better way to fix this (sorry, don't have time right now).

**Comment by cybergarage** [comment]
I have added `configure_macosx`. Please use the script.
