### ISSUE TITLE
No project clinkc.xcodeproj in libs/ios

### ISSUE THREAD

**Issue by SiMet** [cybergarage/mupnpc#12]
I opened upnpbrowser example for ios and project doesn't build because there is no <CyberLink/UPnP.h>.

I found that included project ( ../../../lib/ios/xcode/clinkc.xcodeproj)is not in repository

**Comment by akshayvernekar** [comment]
I have integrated the new changes to the old clinkc.xcodeproj that i had, but i am still getting few compile time errors like "unknown typename BOOL", even though BOOL has been defined in typedef.h. Any pointers Satoshi San.

**Comment by cybergarage** [comment]
I fixed your problems, and uploaded as v3.0.1. Sorry for replying late X-<

**Comment by coramo** [comment]
this problems really fixed now ? I didn't found it.
